version: '3'

services:
  postgres:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_DB: todo_list_api_production
    volumes:
      - ./tmp/postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    command:
      - /bin/sh
      - -c
      - |
          while ! nc -z postgres 5432
          do
            sleep 1
          done
          bundle exec rails db:migrate
          bundle exec rails s
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres
