default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: todo_list_api_development

test:
  <<: *default
  database: todo_list_api_test

production:
  <<: *default
  host: postgres
  database: todo_list_api_production
